// Generated by https://github.com/Nicolas-Reyland/pemog
// Python Extension Module: <@M_Name@>

#define PY_SSIZE_T_CLEAN
#include <Python.h>

static PyObject *<@M_Name@>Error;

<@m_methods_implementations@>

static const char <@m_name@>_doc[?];
PyDoc_STRVAR(<@m_name@>_doc, "<@m_name@> documentation ...");

static PyMethodDef <@M_Name@>Methods[] = {
    <@m_methods_definitions@>
    {NULL, NULL, 0, NULL}        /* Sentinel */
};

static struct PyModuleDef <@m_name@>module = {
    PyModuleDef_HEAD_INIT,
    "<@m_name@>",      /* name of module */
    <@m_name@>_doc,    /* module documentation, may be NULL */
    -1,                     /* size of per-interpreter state of the module,
                            or -1 if the module keeps state in global variables. */
    <@M_Name@>Methods
};

PyMODINIT_FUNC
PyInit_<@m_name@>(void)
{
    PyObject *m;

    m = PyModule_Create(&<@m_name@>module);
    if (m == NULL)
        return NULL;

    <@M_Name@>Error = PyErr_NewException("<@m_name@>.error", NULL, NULL);
    Py_XINCREF(<@M_Name@>Error);
    if (PyModule_AddObject(m, "error", <@M_Name@>Error) < 0) {
        Py_XDECREF(<@M_Name@>Error);
        Py_CLEAR(<@M_Name@>Error);
        Py_DECREF(m);
        return NULL;
    }

    return m;
}
